# Generated by Django 4.2.1 on 2023-05-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Title', models.TextField()),
                ('client', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='media')),
            ],
        ),
    ]
